apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: dev
  name: devdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: FrontEnd
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx