apiVersion: v1
kind: Service
metadata:
  labels:
    app: np-service
    env: dev
  name: np-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
    app: FrontEnd

